# Generated by Django 5.0.6 on 2024-05-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True)),
                ('order_weight', models.IntegerField()),
                ('order_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_adress', models.CharField(max_length=50)),
                ('unload_service', models.BooleanField(default=False)),
                ('manipulator_service', models.BooleanField(default=False)),
                ('additional_info', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ship_date', models.DateField()),
                ('ship_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Orders info',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=20)),
                ('apartment', models.IntegerField(blank=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.client')),
            ],
            options={
                'verbose_name_plural': 'Delivery addresses',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery_app.orderinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_code', models.IntegerField(unique=True)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_max_weight', models.IntegerField()),
                ('vehicle_max_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery_app.orderinfo')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery_app.orderinfo'),
        ),
    ]
