# Generated by Django 5.0.6 on 2024-05-31 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orders__created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_code', models.IntegerField(unique=True)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_max_weight', models.IntegerField()),
                ('vehicle_max_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house', models.IntegerField()),
                ('apartment', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.client')),
            ],
            options={
                'verbose_name_plural': 'Delivery addresses',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True)),
                ('order_weight', models.IntegerField()),
                ('order_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_adress', models.CharField(choices=[('address1', 'Склад №1'), ('address2', 'Склад №2')], max_length=50)),
                ('unload_service', models.BooleanField(default=False)),
                ('manipulator_service', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField()),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('ship_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Підтверджено'), ('on_the_way', 'В дорозі'), ('delivered', 'Доставлено'), ('canceled', 'Відмінено')], default='confirmed', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_app.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='delivery_app.driver')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders info',
            },
        ),
    ]
