# Generated by Django 5.0.6 on 2024-05-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_rename_name_deliveryaddress_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery_app.orderinfo'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery_app.orderinfo'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery_app.orderinfo'),
        ),
    ]
