# Generated by Django 5.0.6 on 2024-05-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_alter_client_orders_alter_driver_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='additional_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
