# Generated by Django 5.0.6 on 2024-05-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0004_alter_orderinfo_additional_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['orders__created_at']},
        ),
        migrations.AlterField(
            model_name='client',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_app.orderinfo'),
        ),
    ]
