# Generated by Django 5.0.6 on 2024-05-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_alter_client_options_alter_client_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-orders__created_at']},
        ),
    ]
