# Generated by Django 5.0.6 on 2024-05-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0006_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['orders__created_at']},
        ),
    ]
