# Generated by Django 5.0.6 on 2024-05-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0007_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='delivery_app.orderinfo'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_orders', to='delivery_app.orderinfo'),
        ),
    ]
