# Generated by Django 5.0.6 on 2024-05-13 19:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0008_alter_client_orders_alter_manager_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['client__created_at']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='orders',
        ),
        migrations.AddField(
            model_name='manager',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 5, 13, 19, 18, 57, 464082, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 19, 19, 9, 171959, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='delivery_app.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='delivery_app.driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to='delivery_app.manager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 19, 20, 23, 59609, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
