# Generated by Django 5.0.6 on 2024-05-13 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0010_alter_client_options_alter_orderinfo_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['orders__created_at']},
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_app.client'),
        ),
    ]
