# Generated by Django 5.0.6 on 2024-05-18 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0013_customuser_alter_deliveryaddress_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.client'),
        ),
    ]
