# Generated by Django 5.0.6 on 2024-05-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0014_alter_deliveryaddress_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
