# Generated by Django 5.0.6 on 2024-05-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0015_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
