# Generated by Django 5.0.6 on 2024-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0017_alter_orderinfo_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='ship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='ship_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
