# Generated by Django 5.0.6 on 2024-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0019_alter_orderinfo_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='apartment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
