# Generated by Django 5.0.6 on 2024-05-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0020_alter_deliveryaddress_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
