# Generated by Django 5.0.6 on 2024-05-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0021_alter_orderinfo_order_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_max_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
